[package]
name = "powermeter"
version = "0.1.0"
authors = ["Michal Sojka <michal.sojka@cvut.cz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
