name: clang-format

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: '.'
        exclude: './benchmarks/cl-bench ./benchmarks/coremark ./benchmarks/coremark-pro ./benchmarks/mem ./benchmarks/tacle-bench ./benchmarks/tinyrenderer ./build ./subproject'
        clangFormatVersion: 10
        style: file
