name: Documentation

on:
  push:
    branches:
      - '*'
    tags: '*'
    paths:
      - 'julia/**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Julia stuff
        uses: actions/cache@v2
        with:
          path: ~/.julia
          key: ${{ runner.os }}-build
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.6
      - name: Install dependencies
        working-directory: julia
        run: julia --project=. -e 'using Pkg; Pkg.instantiate()'
      - name: Install gnuplot
        run: |
          sudo apt update &&
          sudo apt install gnuplot
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
        run: make -C julia/docs
