name: "Complie & Test"
on:
  pull_request:
  push:
  schedule:
    - cron:  '0 0 * * Mon'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v8
      with:
        name: thermac
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
#     - name: Configure
#       run: nix-shell --run "make build/build.ninja"
#     - name: Build subprojects
#       run: nix-shell --run "ninja -C build subprojects/libev/libev.a"
    - name: Register gcc problem matcher # After subprojects to not see their warings
      run: echo "::add-matcher::.github/problem-matchers/gcc.json"
    - name: Build thermobench via make
      run: nix-shell --run "make"
    - name: Run tests
      run: nix-shell --run "cd build && meson test"
    - name: Build thermobench via nix-build
      run: nix-build
#     - name: Aarch64
#       run: nix-build --argstr crossSystem aarch64-linux
